//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using ET;


namespace Cfg
{
   
public sealed class Tables
{
    public TbStart TbStart {get; private set; }

    public Tables() { }
    
    public async ETTask LoadAsync(System.Func<string, ETTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbStart = new TbStart(await loader("tbstart")); 
        tables.Add("TbStart", TbStart);

        TbStart.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbStart.TranslateText(translator); 
    }
}

}
