//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg
{
   
public partial class TbStartScene
{
    private readonly Dictionary<int, StartScene> _dataMap;
    private readonly List<StartScene> _dataList;
    
    public TbStartScene(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, StartScene>();
        _dataList = new List<StartScene>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartScene _v;
            _v = StartScene.DeserializeStartScene(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, StartScene> DataMap => _dataMap;
    public List<StartScene> DataList => _dataList;

    public StartScene GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartScene Get(int key) => _dataMap[key];
    public StartScene this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}