//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg
{

public sealed partial class StartZone :  Bright.Config.BeanBase 
{
    public StartZone(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DBConnection = _buf.ReadString();
        DBName = _buf.ReadString();
        PostInit();
    }

    public static StartZone DeserializeStartZone(ByteBuf _buf)
    {
        return new StartZone(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 数据库地址
    /// </summary>
    public string DBConnection { get; private set; }
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DBName { get; private set; }

    public const int __ID__ = -125142258;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DBConnection:" + DBConnection + ","
        + "DBName:" + DBName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
