//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using ET;


namespace Cfg
{
   
public sealed class Tables
{
    public TbStartMachine TbStartMachine {get; private set; }
    public TbStartProcess TbStartProcess {get; private set; }
    public TbStartScene TbStartScene {get; private set; }
    public TbStartZone TbStartZone {get; private set; }

    public Tables() { }
    
    public async ETTask LoadAsync(System.Func<string, ETTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbStartMachine = new TbStartMachine(await loader("tbstartmachine")); 
        tables.Add("TbStartMachine", TbStartMachine);
        TbStartProcess = new TbStartProcess(await loader("tbstartprocess")); 
        tables.Add("TbStartProcess", TbStartProcess);
        TbStartScene = new TbStartScene(await loader("tbstartscene")); 
        tables.Add("TbStartScene", TbStartScene);
        TbStartZone = new TbStartZone(await loader("tbstartzone")); 
        tables.Add("TbStartZone", TbStartZone);

        TbStartMachine.Resolve(tables); 
        TbStartProcess.Resolve(tables); 
        TbStartScene.Resolve(tables); 
        TbStartZone.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbStartMachine.TranslateText(translator); 
        TbStartProcess.TranslateText(translator); 
        TbStartScene.TranslateText(translator); 
        TbStartZone.TranslateText(translator); 
    }
}

}
