//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using ET;


namespace Cfg
{
   
public sealed class Tables
{
    public TBStartScene TBStartScene {get; private set; }
    public TBStart TBStart {get; private set; }

    public Tables() { }
    
    public async ETTask LoadAsync(System.Func<string, ETTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TBStartScene = new TBStartScene(await loader("tbstartscene")); 
        tables.Add("TBStartScene", TBStartScene);
        TBStart = new TBStart(await loader("tbstart")); 
        tables.Add("TBStart", TBStart);

        TBStartScene.Resolve(tables); 
        TBStart.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TBStartScene.TranslateText(translator); 
        TBStart.TranslateText(translator); 
    }
}

}
