//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg
{
   
public partial class TbStartProcess
{
    private readonly Dictionary<int, StartProcess> _dataMap;
    private readonly List<StartProcess> _dataList;
    private static TbStartProcess _instance;
    
    public TbStartProcess(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, StartProcess>();
        _dataList = new List<StartProcess>();
        _instance = this;
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartProcess _v;
            _v = StartProcess.DeserializeStartProcess(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public static TbStartProcess Instance => _instance;
    public Dictionary<int, StartProcess> DataMap => _dataMap;
    public List<StartProcess> DataList => _dataList;

    public StartProcess GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartProcess Get(int key) => _dataMap[key];
    public StartProcess this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}