//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg
{
   
public partial class TbStartMachine
{
    private readonly Dictionary<int, StartMachine> _dataMap;
    private readonly List<StartMachine> _dataList;
    private static TbStartMachine _instance;
    
    public TbStartMachine(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, StartMachine>();
        _dataList = new List<StartMachine>();
        _instance = this;
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartMachine _v;
            _v = StartMachine.DeserializeStartMachine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public static TbStartMachine Instance => _instance;
    public Dictionary<int, StartMachine> DataMap => _dataMap;
    public List<StartMachine> DataList => _dataList;

    public StartMachine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartMachine Get(int key) => _dataMap[key];
    public StartMachine this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}